In [25]:
import pandas as pd
import numpy as np

In [ ]:
demo = pd.read_csv('../assets/demo.csv')
demo['birth_year'] = demo['birth_year'].astype(int)
demo.head()

,user_id,account_start_date,birth_year,gender,marital_status,family_income_segment_code,individual_income_segment_code
0,27616,1975-04-15,1961,F,,06,04
1,14619,1971-01-31,1943,F,1,04,09
2,13595,1960-11-24,1952,F,1,07,07
3,31656,1972-05-25,1952,F,2,03,13
4,6179,1957-06-02,1939,M,2,01,12

In [ ]:
print(demo.shape)
print(demo[['user_id']].drop_duplicates().shape)

(52762, 7)
(52762, 1)

In [19]:
card = pd.read_csv('../assets/card_info.csv')
card.head()

   user_id  bill_cyc  cr_lmt_amt  card_no
0        0      17.0      244000        0
1        1      12.0      361000        1
2        2      12.0      385000        2
3        3      15.0      518000        3
4        4      15.0      889000        4

In [9]:
print(card.shape)
print(card[['user_id']].drop_duplicates().shape)

(60296, 4)
(52762, 1)

In [14]:
card_agg = pd.DataFrame(card.groupby('user_id').agg(cnt=("user_id","count"))).reset_index()
card_agg[card_agg['cnt']>1]

       user_id  cnt
8            8    2
14          14    2
18          18    2
28          28    2
30          30    2
...        ...  ...
52614    52614    2
52618    52618    2
52635    52635    2
52654    52654    2
52692    52692    2

[7043 rows x 2 columns]

In [15]:
card[card['user_id'] == 8]

   user_id  bill_cyc  cr_lmt_amt  card_no
8        8      16.0     1112000        8
9        8      14.0      963000        9

In [16]:
print(card[['card_no']].drop_duplicates().shape)

(60296, 1)

In [7]:
card_trans = pd.read_csv('../assets/cc_txn.csv')
card_trans["txn_dt"] = pd.to_datetime(card_trans["txn_dt"], errors="coerce")
card_trans["year_month"] = card_trans["txn_dt"].dt.to_period("M").astype(str)
card_trans["month"] = card_trans["txn_dt"].dt.month
print(card_trans.shape)
card_trans.head()

(3223075, 7)

         mcc     txn_dt  user_id   txn_amt  card_no year_month  month
0  mcc_cat10 2017-04-12    17863   16391.0  21616.0    2017-04      4
1  mcc_cat11 2017-07-12     7682  117200.0   9438.0    2017-07      7
2  mcc_cat12 2017-05-23    33603   55602.0  39476.0    2017-05      5
3   mcc_cat4 2017-11-03    44040   38894.0  50979.0    2017-11     11
4  mcc_cat14 2017-12-18     4529   29524.0   5582.0    2017-12     12

In [19]:
print(card_trans['txn_dt'].min())
print(card_trans['txn_dt'].max())

2017-01-26
2017-12-31

In [18]:
card_type_agg = pd.DataFrame(card_trans.groupby(['user_id', 'year_month', 'mcc', 'card_no']).agg(sum_amt=('txn_amt', 'sum'), avg_amt=('txn_amt', 'mean'), cnt_trans=("user_id","count"))).reset_index()
card_type_agg

         user_id year_month        mcc  card_no  sum_amt  avg_amt  cnt_trans
0              0    2017-01   mcc_cat5      0.0  19974.0  19974.0          1
1              0    2017-02   mcc_cat1      0.0  37788.0  37788.0          1
2              0    2017-02  mcc_cat11      0.0  18490.0  18490.0          1
3              0    2017-02   mcc_cat2      0.0   3914.0   3914.0          1
4              0    2017-02   mcc_cat4      0.0  13402.0  13402.0          1
...          ...        ...        ...      ...      ...      ...        ...
2804845    52761    2017-11   mcc_cat3  60295.0  20051.0  20051.0          1
2804846    52761    2017-11   mcc_cat4  60295.0   3312.0   3312.0          1
2804847    52761    2017-11   mcc_cat6  60295.0   4251.0   4251.0          1
2804848    52761    2017-12  mcc_cat15  60295.0  78034.0  78034.0          1
2804849    52761    2017-12   mcc_cat9  60295.0  18524.0  18524.0          1

[2804850 rows x 7 columns]

In [12]:
card_agg = pd.DataFrame(card_trans.groupby(['user_id', 'year_month', 'card_no']).agg(sum_amt=('txn_amt', 'sum'), avg_amt=('txn_amt', 'mean'), cnt_trans=("user_id","count"))).reset_index()
card_agg

        user_id year_month  card_no   sum_amt       avg_amt  cnt_trans
0             0    2017-01      0.0   19974.0  19974.000000          1
1             0    2017-02      0.0  114769.0  16395.571429          7
2             0    2017-03      0.0  120157.0  24031.400000          5
3             0    2017-04      0.0   21234.0  21234.000000          1
4             0    2017-05      0.0  306455.0  34050.555556          9
...         ...        ...      ...       ...           ...        ...
694659    52761    2017-08  60295.0   45230.0  15076.666667          3
694660    52761    2017-09  60295.0   37784.0  18892.000000          2
694661    52761    2017-10  60295.0  121346.0  40448.666667          3
694662    52761    2017-11  60295.0  152531.0  21790.142857          7
694663    52761    2017-12  60295.0   96558.0  48279.000000          2

[694664 rows x 6 columns]

In [20]:
card_agg = card_agg.merge(card, on=['user_id', 'card_no'], how='left')
card_agg

,user_id,year_month,card_no,sum_amt,avg_amt,cnt_trans,bill_cyc,cr_lmt_amt
0,0,2017-01,0.0,19974.0,19974.000000,1,17.0,244000
1,0,2017-02,0.0,114769.0,16395.571429,7,17.0,244000
2,0,2017-03,0.0,120157.0,24031.400000,5,17.0,244000
3,0,2017-04,0.0,21234.0,21234.000000,1,17.0,244000
4,0,2017-05,0.0,306455.0,34050.555556,9,17.0,244000
...,...,...,...,...,...,...,...,...
694659,52761,2017-08,60295.0,45230.0,15076.666667,3,13.0,293000
694660,52761,2017-09,60295.0,37784.0,18892.000000,2,13.0,293000
694661,52761,2017-10,60295.0,121346.0,40448.666667,3,13.0,293000
694662,52761,2017-11,60295.0,152531.0,21790.142857,7,13.0,293000
694663,52761,2017-12,60295.0,96558.0,48279.000000,2,13.0,293000

In [ ]:
'''
0 -> เกินวงเงิน
1 -> ไม่เกินวงเงิน
'''
card_agg['utilization_ratio'] = (card_agg['sum_amt']) / card_agg['cr_lmt_amt'] *100
card_agg['tag'] = np.where(card_agg['utilization_ratio']>100, 0, 1)
card_agg

,user_id,year_month,card_no,sum_amt,avg_amt,cnt_trans,bill_cyc,cr_lmt_amt,utilization_ratio,tag
0,0,2017-01,0.0,19974.0,19974.000000,1,17.0,244000,8.186066,ไม่เกิน limit
1,0,2017-02,0.0,114769.0,16395.571429,7,17.0,244000,47.036475,ไม่เกิน limit
2,0,2017-03,0.0,120157.0,24031.400000,5,17.0,244000,49.244672,ไม่เกิน limit
3,0,2017-04,0.0,21234.0,21234.000000,1,17.0,244000,8.702459,ไม่เกิน limit
4,0,2017-05,0.0,306455.0,34050.555556,9,17.0,244000,125.596311,เกิน limit
...,...,...,...,...,...,...,...,...,...,...
694659,52761,2017-08,60295.0,45230.0,15076.666667,3,13.0,293000,15.436860,ไม่เกิน limit
694660,52761,2017-09,60295.0,37784.0,18892.000000,2,13.0,293000,12.895563,ไม่เกิน limit
694661,52761,2017-10,60295.0,121346.0,40448.666667,3,13.0,293000,41.415017,ไม่เกิน limit
694662,52761,2017-11,60295.0,152531.0,21790.142857,7,13.0,293000,52.058362,ไม่เกิน limit
694663,52761,2017-12,60295.0,96558.0,48279.000000,2,13.0,293000,32.954949,ไม่เกิน limit

In [27]:
card_agg['tag'].value_counts()

tag
ไม่เกิน limit    557104
เกิน limit       137560
Name: count, dtype: int64

In [ ]:
'''
1 user_id มี 12 transaction
ขนาด: 633,144 แถว
max_sa_bal: ยอดคงเหลือสูงสุดของบัญชีออมทรัพย์ในเดือนนั้น
'''
sa_bal = pd.read_csv('../assets/sa_bal.csv')
sa_bal.head()

   user_id  mm  max_sa_bal
0        0   1    535052.0
1        0  10         0.0
2        0  11    161530.0
3        0  12    345973.0
4        0   2    646838.0

In [22]:
sa_bal[['user_id']].nunique()*12

user_id    633144
dtype: int64

In [2]:
''''
ขนาด: 490,599 แถว
1 user_id อาจมี transaction ไม่ครบทุกเดือน
'''
dtxn = pd.read_csv('../assets/dtxn.csv')
dtxn.head()

   user_id  mm   amt_in  amt_out
0        0   1  17725.0   4490.0
1        0   2  12431.0  29286.0
2        0   3  86274.0      0.0
3        0   4      0.0  14328.0
4        0   5  29829.0  84557.0

In [3]:
dtxn['net_flow'] = dtxn['amt_in'] - dtxn['amt_out']
dtxn

        user_id  mm   amt_in   amt_out  net_flow
0             0   1  17725.0    4490.0   13235.0
1             0   2  12431.0   29286.0  -16855.0
2             0   3  86274.0       0.0   86274.0
3             0   4      0.0   14328.0  -14328.0
4             0   5  29829.0   84557.0  -54728.0
...         ...  ..      ...       ...       ...
490594    52761   3      0.0   79664.0  -79664.0
490595    52761   5  35901.0       0.0   35901.0
490596    52761   6   1306.0   37114.0  -35808.0
490597    52761   8      0.0  108236.0 -108236.0
490598    52761   9      0.0   88520.0  -88520.0

[490599 rows x 5 columns]

In [24]:
dtxn[['user_id']].nunique()*12

user_id    633144
dtype: int64

In [26]:
dtxn_agg = pd.DataFrame(dtxn.groupby('user_id').agg(cnt=("user_id","count"))).reset_index()
dtxn_agg

       user_id  cnt
0            0    8
1            1   10
2            2    9
3            3   11
4            4    9
...        ...  ...
52757    52757   10
52758    52758   10
52759    52759    9
52760    52760    7
52761    52761    9

[52762 rows x 2 columns]

In [29]:
dtxn[dtxn['user_id'] == 0]

   user_id  mm   amt_in  amt_out
0        0   1  17725.0   4490.0
1        0   2  12431.0  29286.0
2        0   3  86274.0      0.0
3        0   4      0.0  14328.0
4        0   5  29829.0  84557.0
5        0   6      0.0   8853.0
6        0   7   1393.0  26702.0
7        0   9      0.0   9039.0